version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: distribuidora
    ports:
      - "5432:5432"
    volumes:
      - controleloja_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: senha123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ../Sistema-PDV
    container_name: fastapi-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:senha123@postgres:5432/distribuidora
    ports:
      - "8000:8000"

  frontend:
    build: ../Sistema-PDV_web
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  controleloja_postgres_data:
    external: true
  pgadmin_data:
