"""add total_value

Revision ID: 10334ac7b8c3
Revises: a95fa8aa5f69
Create Date: 2026-04-03 16:13:49.900113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10334ac7b8c3'
down_revision: Union[str, Sequence[str], None] = 'a95fa8aa5f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'total_value')
    # ### end Alembic commands ###
