"""create column total_value in purchases table

Revision ID: 894043c526f6
Revises: b6a74c368111
Create Date: 2026-04-13 11:33:49.888544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894043c526f6'
down_revision: Union[str, Sequence[str], None] = 'b6a74c368111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'total_value')
    # ### end Alembic commands ###
