"""fix relationship products-product_sub_category

Revision ID: a95fa8aa5f69
Revises: df7417d0828a
Create Date: 2026-03-10 14:44:07.046960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95fa8aa5f69'
down_revision: Union[str, Sequence[str], None] = 'df7417d0828a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
